language: node_js

node_js:
  - "lts/*"

script: npm build

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: src
  provider: pages
  skip_cleanup: true
  target_branch: master
